# Generated by Django 4.2.20 on 2025-04-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CensusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('electorate', models.CharField(choices=[('Moresby South', 'Moresby South'), ('Moresby Northeast', 'Moresby Northeast'), ('Moresby Northwest', 'Moresby Northwest'), ('Motukoitabu', 'Motukoitabu')], max_length=50)),
                ('reason', models.TextField()),
                ('date_recorded', models.DateField()),
            ],
        ),
    ]
