# Generated by Django 4.2.20 on 2025-04-30 15:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_birthsregistry_crpregistry_deathsregistry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthsRegistry',
        ),
        migrations.DeleteModel(
            name='CRPRegistry',
        ),
        migrations.DeleteModel(
            name='DeathsRegistry',
        ),
        migrations.DeleteModel(
            name='DisabilityRegistry',
        ),
        migrations.DeleteModel(
            name='LawRegistry',
        ),
        migrations.DeleteModel(
            name='MarriageRegistry',
        ),
        migrations.DeleteModel(
            name='MigrationRegistry',
        ),
        migrations.DeleteModel(
            name='Population',
        ),
        migrations.DeleteModel(
            name='ProjectsRegistry',
        ),
        migrations.DeleteModel(
            name='WardOfficial',
        ),
        migrations.RemoveField(
            model_name='censusrecord',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='censusrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/images/'), upload_to='images/'),
        ),
    ]
